// <auto-generated />
using EFGetStarted;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace SchoolCourse.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20210505145241_ToTable")]
    partial class ToTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("EFGetStarted.GarageDoorModel", b =>
                {
                    b.Property<int>("GarageDoorModelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Layout")
                        .HasColumnType("TEXT");

                    b.Property<string>("ModelName")
                        .HasColumnType("TEXT");

                    b.Property<string>("WindCode")
                        .HasColumnType("TEXT");

                    b.HasKey("GarageDoorModelId");

                    b.ToTable("GarageDoorModels");
                });

            modelBuilder.Entity("EFGetStarted.Section", b =>
                {
                    b.Property<int>("SectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("SectionName")
                        .HasColumnType("TEXT");

                    b.HasKey("SectionId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("GarageDoorModelSection", b =>
                {
                    b.Property<int>("GarageDoorModelsGarageDoorModelId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SectionsSectionId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GarageDoorModelsGarageDoorModelId", "SectionsSectionId");

                    b.HasIndex("SectionsSectionId");

                    b.ToTable("GarageDoorModelSection");
                });

            modelBuilder.Entity("GarageDoorModelSection", b =>
                {
                    b.HasOne("EFGetStarted.GarageDoorModel", null)
                        .WithMany()
                        .HasForeignKey("GarageDoorModelsGarageDoorModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EFGetStarted.Section", null)
                        .WithMany()
                        .HasForeignKey("SectionsSectionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
